spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: gdsbwhjsnsjkdndehjdbdshdsmnhsgfsvswjsdsffvbfgdfvewvfweqfjugwqifbliqebcilevbcehfuyjhqquyjkq